### ISSUE TITLE
Cannot hide parts of the structure

### ISSUE THREAD

**Issue by fdtomasi** [raphael-cch/latex-tree#4]
Thanks for the great package.

I cannot fold part of the structure with the corresponding arrow close to the name of the section/subsection: the click is interpreted as a normal click on the name.

**Comment by raphael-cch** [comment]
Indeed currently the arrow does not fold the tree structure, but that shouldn't be too difficult to add. I'll try to do it over the weekend.

**Comment by raphael-cch** [comment]
This is now added in [v0.4.0](https://github.com/raphael-cch/latex-tree/releases/tag/v0.4.0)!
